### ISSUE TITLE
IDV60801.94868 - MELBOURNE REGIONAL OFFICE, VIC - Returning 404

### ISSUE THREAD

**Issue by jufemaiz** [thepatrick/BOMservations#3]
http://www.bom.gov.au/fwo/IDV60801/IDV60801.94868.json is returning a 404 error.

Last known date (for me anyhow): 2015-01-06 15:00:00 +1100

**Comment by jufemaiz** [comment]
New location for Melbourne CBD weather observations and forecasts
Tuesday 9 December 2014 will mark the 'passing of the baton' as, after 106 years in operation, the station on La Trobe Street in Melbourne will be replaced by Melbourne (Olympic Park) as the official weather observation and forecast location for the city of Melbourne.

The official record of weather observations for Melbourne extends back to 1855, with a few breaks. It draws on observations from several locations, including Flagstaff Gardens (1858-1863), the Melbourne Observatory at the Botanic Gardens (1863-1908) and the Royal Society of Victoria on La Trobe Street (1908-2014).

http://www.bom.gov.au/weather-services/announcements/vic/latrobe-site-closure.shtml

**Comment by jufemaiz** [comment]
http://www.bom.gov.au/products/IDV60801/IDV60801.95936.shtml

**Comment by thepatrick** [comment]
Thanks for this, much appreciated!
